${frameworkfolder}/tools/classes
${frameworkfolder}/petrinetWithTransits/classes
${dependenciesfolder}/synthesizer/petriGames/classes
${dependenciesfolder}/logics/classes
${dependenciesfolder}/modelchecker/classes
${dependenciesfolder}/synthesizer/symbolicalgorithms/bddapproach/classes
${dependenciesfolder}/synthesizer/boundedalgorithms/classes
${libfolder}/commons-io-2.4/commons-io-2.4.jar
${libfolder}/apt/apt4adam.jar
${libfolder}/commons-collections4-4.0/commons-collections4-4.0.jar
${libfolder}/antlr-4.5.1/antlr-4.5.1-complete.jar
${libfolder}/javaBDD/javabdd-1.0b2.jar
${libfolder}/trove-3.0.3/trove-3.0.3.jar
