${mainfolder}/tools/classes
${mainfolder}/ds/classes
${mainfolder}/logic/classes
${mainfolder}/generators/classes
${mainfolder}/symbolicalgorithms/classes
${mainfolder}/boundedalgorithms/classes
${libfolder}/antlr-4.5.1/antlr-4.5.1-complete.jar
${libfolder}/commons-collections4-4.0/commons-collections4-4.0.jar
${libfolder}/commons-io-2.4/commons-io-2.4.jar
${libfolder}/apt/apt4adam.jar
${libfolder}/javaBDD/javabdd-1.0b2.jar
