${mainfolder}/tools/classes
${mainfolder}/petrinetWithTransits/classes
${mainfolder}/petriGames/classes
${mainfolder}/logics/classes
${mainfolder}/modelchecking/classes
${mainfolder}/symbolicalgorithms/bddapproach/classes
${mainfolder}/boundedalgorithms/classes
${libfolder}/apt/apt4adam.jar
${libfolder}/commons-collections4-4.0/commons-collections4-4.0.jar
