${frameworkfolder}/tools/classes
${frameworkfolder}/petrinetWithTransits/classes
${dependenciesfolder}/synthesizer/petriGames/classes
${dependenciesfolder}/synthesizer/symbolicalgorithms/bddapproach/classes
${dependenciesfolder}/synthesizer/symbolicalgorithms/mtbddapproach/classes
${libfolder}/apt/apt4adam.jar
${libfolder}/adam_protocol.jar
${libfolder}/antlr-4.5.1/antlr-4.5.1-complete.jar
${libfolder}/commons-io-2.4/commons-io-2.4.jar
${libfolder}/commons-collections4-4.0/commons-collections4-4.0.jar
${libfolder}/javaBDD/javabdd-1.0b2.jar
